export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubik’s cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
    'Capture the innocence and joy of a child playing in a park. Use natural lighting and candid expressions to highlight genuine emotions.',
    'Photograph a military veteran in uniform. Use strong, directional lighting to emphasize the details and textures, conveying a sense of their experiences.',
    'Capture a street performer in action amidst a bustling city. Use a blurred background to emphasize the subject and show movement.',
    'Create a stylized portrait of an entrepreneur against a city skyline. Use dramatic lighting and post-processing techniques to create a futuristic look.',
    'Capture the portrait of an old fisherman at sea. Use natural light and capture the weathered textures of the face to tell their story.',
    'Photograph a professional dancer expressing emotion through their movements. Use dramatic lighting and high contrast to emphasize their form and passion.',
    'Capture a joyful portrait of someone laughing in the rain. Use high shutter speed to freeze the raindrops and a wide aperture to focus on the subject.',
    'Photograph a lone hiker on a mountain peak. Use the golden hour light to create a sense of solitude and achievement.',
    'Capture an athlete in action during a game. Use fast shutter speed to freeze motion and close-up shots to show intensity and determination.',
    'Create a whimsical portrait of a person in a dreamy, natural environment. Use soft lighting and pastel colors to convey a sense of tranquility.',
    'Recreate the essence of autumn by depicting a tree-lined boulevard covered in vibrant, multicolored leaves. Be meticulous with details, from the textures of the leaves to the play of light and shadows.',
    'Emulate the aesthetic of the 1920s by capturing a model in vintage attire against a backdrop of an old brick building. Pay attention to elements like contrast and texture to make the scene feel as if it’s been plucked from a different era.',
    'Capture a serene moment between a child and their pet. Focus on their expressions and body language to convey their bond. Use warm, soft colors to reflect the mood of tranquility. One of the best prompts for ai art right here.',
    'Capture a bustling city street at dusk with people and vehicles under glowing neon lights. Use a low-angle shot to capture the grandeur of the skyscrapers and the vibrant atmosphere of the city.',
    'Create a high-resolution photo of everyday objects, like a coffee cup or a pair of glasses, set against a minimalist background. Focus on details and textures to elevate the ordinary into something extraordinary.',
    'Design an anime scene depicting the last stand of a group of warriors against an army of monsters. Use sharp contrasts of light and dark to dramatize the scene and emphasize the expressions of determination on the warriors’ faces.',
    'Illustrate an anime scene of a sailor navigating the high seas on a fantastical ship, encountering a group of sirens. Use a wide color range for the sea and sky, and accentuate the expressions of the sailor and sirens.',
    'Design an anime-style mecha warrior ready for battle, complete with heavy armor and futuristic weapons. Use dynamic lines and a strong color contrast to accentuate the power and complexity of the design.',
    'Draw an anime-style magic school, filled with students practicing their spells and mystical creatures roaming around. Use a vibrant color palette and intricate details to make the magic come alive.',
];